game.fps=60
game.ups=150
game.original_tile_size=32
game.max_screen_column=25
game.max_screen_row=13
game.scale=1.5
# Online multiplayer server URLs
server.1.url=ws://localhost:8080/ws
server.2.url=ws://localhost:8081/ws
server.3.url=ws://localhost:8082/ws